# Generated by Django 5.2.4 on 2025-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('Title', models.CharField(max_length=255)),
                ('Company', models.CharField(blank=True, max_length=255, null=True)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('JobDescription', models.TextField(blank=True, null=True)),
                ('JobRequirment', models.TextField(blank=True, null=True)),
                ('RequiredQual', models.TextField(blank=True, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('Month', models.IntegerField(blank=True, null=True)),
                ('IT', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
